In [1]:
import FinanceDataReader as fdr
from sklearn.preprocessing import StandardScaler
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd

plt.rcParams["figure.figsize"] = (14,4)
plt.rcParams['lines.linewidth'] = 2
plt.rcParams["axes.grid"] = True

In [2]:
stocks = fdr.StockListing('S&P500')

In [3]:
stocks

,Symbol,Name,Sector,Industry
0,MMM,3M,Industrials,Industrial Conglomerates
1,ABT,Abbott Laboratories,Health Care,Health Care Equipment
2,ABBV,AbbVie,Health Care,Pharmaceuticals
3,ABMD,Abiomed,Health Care,Health Care Equipment
4,ACN,Accenture,Information Technology,IT Consulting & Other Services
...,...,...,...,...
500,YUM,Yum! Brands,Consumer Discretionary,Restaurants
501,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments
502,ZBH,Zimmer Biomet,Health Care,Health Care Equipment
503,ZION,Zions Bancorp,Financials,Regional Banks
504,ZTS,Zoetis,Health Care,Pharmaceuticals

In [4]:
cnt = 0
stock_name = []
init_len = len(fdr.DataReader('MMM', '2017'))
for idx in stocks['Symbol']:
    dataset_iter = fdr.DataReader(idx,'2017')
    
    dataset_iter.drop(['Open','High','Low','Close','Volume'], axis = 'columns', inplace = True)
    
    dataset_iter_target = dataset_iter
    dataset_iter_sequence = dataset_iter
    
    # 신규 상장 제거
    if len(dataset_iter) < init_len:
        continue
    
    stock_name.append(idx)
    
    std_scaler = StandardScaler()
    std_train = std_scaler.fit_transform(dataset_iter_sequence)
    std_dataset = pd.DataFrame(std_train, columns=dataset_iter_sequence.columns,
                         index=list(dataset_iter_sequence.index.values))
    
    for i in range(1,240):
        name2 = 'Change' + str(i)
        std_dataset[name2] = std_dataset['Change'].shift(-i)
    std_dataset = std_dataset.dropna(axis=0)
    std_train_dataset = std_dataset[:-230]
    std_test_dataset = std_dataset[-230:]
    
    name3 = 'testData/s' + str(cnt) + '.csv'
    std_test_dataset.to_csv(name3)
    if idx == 'MMM':
        train_set = std_train_dataset
    else :
        train_set = pd.concat([train_set,std_train_dataset], axis = 0)
    
    name = 'Change' + str(cnt)
    dataset_iter_target.columns = [name]
    if idx == 'MMM':
        dataset_target = dataset_iter_target
    else :
        dataset_target = pd.concat([dataset_target,dataset_iter_target], axis = 1)
    print("iter %d is complete" % cnt)
    cnt+=1

iter 0 is complete
iter 1 is complete
iter 2 is complete
iter 3 is complete
iter 4 is complete
iter 5 is complete
iter 6 is complete
iter 7 is complete
iter 8 is complete
iter 9 is complete
iter 10 is complete
iter 11 is complete
iter 12 is complete
iter 13 is complete
iter 14 is complete
iter 15 is complete
iter 16 is complete
iter 17 is complete
iter 18 is complete
iter 19 is complete
iter 20 is complete
iter 21 is complete
iter 22 is complete
iter 23 is complete
iter 24 is complete
iter 25 is complete
iter 26 is complete
iter 27 is complete
iter 28 is complete
iter 29 is complete
iter 30 is complete
iter 31 is complete
iter 32 is complete
iter 33 is complete
iter 34 is complete
iter 35 is complete
iter 36 is complete
iter 37 is complete
iter 38 is complete
iter 39 is complete
iter 40 is complete
iter 41 is complete
iter 42 is complete
iter 43 is complete
iter 44 is complete
iter 45 is complete
iter 46 is complete
iter 47 is complete
iter 48 is complete
iter 49 is complete
iter 50 is complete
iter 51 is complete
iter 52 is complete
iter 53 is complete
iter 54 is complete
iter 55 is complete
iter 56 is complete
iter 57 is complete
iter 58 is complete
iter 59 is complete
iter 60 is complete
iter 61 is complete
iter 62 is complete
iter 63 is complete
iter 64 is complete
iter 65 is complete
iter 66 is complete
iter 67 is complete
iter 68 is complete
iter 69 is complete
iter 70 is complete
iter 71 is complete
iter 72 is complete
iter 73 is complete
iter 74 is complete
iter 75 is complete
iter 76 is complete
iter 77 is complete
iter 78 is complete
iter 79 is complete
iter 80 is complete
iter 81 is complete
iter 82 is complete
iter 83 is complete
iter 84 is complete
iter 85 is complete
iter 86 is complete
iter 87 is complete
iter 88 is complete
iter 89 is complete
iter 90 is complete
iter 91 is complete
iter 92 is complete
iter 93 is complete
iter 94 is complete
iter 95 is complete
iter 96 is complete
iter 97 is complete
iter 98 is complete
iter 99 is complete
iter 100 is complete
iter 101 is complete
iter 102 is complete
iter 103 is complete
iter 104 is complete
iter 105 is complete
iter 106 is complete
iter 107 is complete
iter 108 is complete
iter 109 is complete
iter 110 is complete
iter 111 is complete
iter 112 is complete
iter 113 is complete
iter 114 is complete
iter 115 is complete
iter 116 is complete
iter 117 is complete
iter 118 is complete
iter 119 is complete
iter 120 is complete
iter 121 is complete
iter 122 is complete
iter 123 is complete
iter 124 is complete
iter 125 is complete
iter 126 is complete
iter 127 is complete
iter 128 is complete
iter 129 is complete
iter 130 is complete
iter 131 is complete
iter 132 is complete
iter 133 is complete
iter 134 is complete
iter 135 is complete
iter 136 is complete
iter 137 is complete
iter 138 is complete
iter 139 is complete
iter 140 is complete
iter 141 is complete
iter 142 is complete
iter 143 is complete
iter 144 is complete
iter 145 is complete
iter 146 is complete
iter 147 is complete
iter 148 is complete
iter 149 is complete
iter 150 is complete
iter 151 is complete
iter 152 is complete
iter 153 is complete
iter 154 is complete
iter 155 is complete
iter 156 is complete
iter 157 is complete
iter 158 is complete
iter 159 is complete
iter 160 is complete
iter 161 is complete
iter 162 is complete
iter 163 is complete
iter 164 is complete
iter 165 is complete
iter 166 is complete
iter 167 is complete
iter 168 is complete
iter 169 is complete
iter 170 is complete
iter 171 is complete
iter 172 is complete
iter 173 is complete
iter 174 is complete
iter 175 is complete
iter 176 is complete
iter 177 is complete
iter 178 is complete
iter 179 is complete
iter 180 is complete
iter 181 is complete
iter 182 is complete
iter 183 is complete
iter 184 is complete
iter 185 is complete
iter 186 is complete
iter 187 is complete
iter 188 is complete
iter 189 is complete
iter 190 is complete
iter 191 is complete
iter 192 is complete
iter 193 is complete
iter 194 is complete
iter 195 is complete
iter 196 is complete
iter 197 is complete
iter 198 is complete
iter 199 is complete
iter 200 is complete
iter 201 is complete
iter 202 is complete
iter 203 is complete
iter 204 is complete
iter 205 is complete
iter 206 is complete
iter 207 is complete
iter 208 is complete
iter 209 is complete
iter 210 is complete
iter 211 is complete
iter 212 is complete
iter 213 is complete
iter 214 is complete
iter 215 is complete
iter 216 is complete
iter 217 is complete
iter 218 is complete
iter 219 is complete
iter 220 is complete
iter 221 is complete
iter 222 is complete
iter 223 is complete
iter 224 is complete
iter 225 is complete
iter 226 is complete
iter 227 is complete
iter 228 is complete
iter 229 is complete
iter 230 is complete
iter 231 is complete
iter 232 is complete
iter 233 is complete
iter 234 is complete
iter 235 is complete
iter 236 is complete
iter 237 is complete
iter 238 is complete
iter 239 is complete
iter 240 is complete
iter 241 is complete
iter 242 is complete
iter 243 is complete
iter 244 is complete
iter 245 is complete
iter 246 is complete
iter 247 is complete
iter 248 is complete
iter 249 is complete
iter 250 is complete
iter 251 is complete
iter 252 is complete
iter 253 is complete
iter 254 is complete
iter 255 is complete
iter 256 is complete
iter 257 is complete
iter 258 is complete
iter 259 is complete
iter 260 is complete
iter 261 is complete
iter 262 is complete
iter 263 is complete
iter 264 is complete
iter 265 is complete
iter 266 is complete
iter 267 is complete
iter 268 is complete
iter 269 is complete
iter 270 is complete
iter 271 is complete
iter 272 is complete
iter 273 is complete
iter 274 is complete
iter 275 is complete
iter 276 is complete
iter 277 is complete
iter 278 is complete
iter 279 is complete
iter 280 is complete
iter 281 is complete
iter 282 is complete
iter 283 is complete
iter 284 is complete
iter 285 is complete
iter 286 is complete
iter 287 is complete
iter 288 is complete
iter 289 is complete
iter 290 is complete
iter 291 is complete
iter 292 is complete
iter 293 is complete
iter 294 is complete
iter 295 is complete
iter 296 is complete
iter 297 is complete
iter 298 is complete
iter 299 is complete
iter 300 is complete
iter 301 is complete
iter 302 is complete
iter 303 is complete
iter 304 is complete
iter 305 is complete
iter 306 is complete
iter 307 is complete
iter 308 is complete
iter 309 is complete
iter 310 is complete
iter 311 is complete
iter 312 is complete
iter 313 is complete
iter 314 is complete
iter 315 is complete
iter 316 is complete
iter 317 is complete
iter 318 is complete
iter 319 is complete
iter 320 is complete
iter 321 is complete
iter 322 is complete
iter 323 is complete
iter 324 is complete
iter 325 is complete
iter 326 is complete
iter 327 is complete
iter 328 is complete
iter 329 is complete
iter 330 is complete
iter 331 is complete
iter 332 is complete
iter 333 is complete
iter 334 is complete
iter 335 is complete
iter 336 is complete
iter 337 is complete
iter 338 is complete
iter 339 is complete
iter 340 is complete
iter 341 is complete
iter 342 is complete
iter 343 is complete
iter 344 is complete
iter 345 is complete
iter 346 is complete
iter 347 is complete
iter 348 is complete
iter 349 is complete
iter 350 is complete
iter 351 is complete
iter 352 is complete
iter 353 is complete
iter 354 is complete
iter 355 is complete
iter 356 is complete
iter 357 is complete
iter 358 is complete
iter 359 is complete
iter 360 is complete
iter 361 is complete
iter 362 is complete
iter 363 is complete
iter 364 is complete
iter 365 is complete
iter 366 is complete
iter 367 is complete
iter 368 is complete
iter 369 is complete
iter 370 is complete
iter 371 is complete
iter 372 is complete
iter 373 is complete
iter 374 is complete
iter 375 is complete
iter 376 is complete
iter 377 is complete
iter 378 is complete
iter 379 is complete
iter 380 is complete
iter 381 is complete
iter 382 is complete
iter 383 is complete
iter 384 is complete
iter 385 is complete
iter 386 is complete
iter 387 is complete
iter 388 is complete
iter 389 is complete
iter 390 is complete
iter 391 is complete
iter 392 is complete
iter 393 is complete
iter 394 is complete
iter 395 is complete

iter 396 is complete
iter 397 is complete
iter 398 is complete
iter 399 is complete
iter 400 is complete
iter 401 is complete
iter 402 is complete
iter 403 is complete
iter 404 is complete
iter 405 is complete
iter 406 is complete
iter 407 is complete
iter 408 is complete
iter 409 is complete
iter 410 is complete
iter 411 is complete
iter 412 is complete
iter 413 is complete
iter 414 is complete
iter 415 is complete
iter 416 is complete
iter 417 is complete
iter 418 is complete
iter 419 is complete
iter 420 is complete
iter 421 is complete
iter 422 is complete
iter 423 is complete
iter 424 is complete
iter 425 is complete
iter 426 is complete
iter 427 is complete
iter 428 is complete
iter 429 is complete
iter 430 is complete
iter 431 is complete
iter 432 is complete
iter 433 is complete
iter 434 is complete
iter 435 is complete
iter 436 is complete
iter 437 is complete
iter 438 is complete
iter 439 is complete
iter 440 is complete
iter 441 is complete
iter 442 is complete
iter 443 is complete
iter 444 is complete
iter 445 is complete
iter 446 is complete
iter 447 is complete
iter 448 is complete
iter 449 is complete
iter 450 is complete
iter 451 is complete
iter 452 is complete
iter 453 is complete
iter 454 is complete
iter 455 is complete
iter 456 is complete
iter 457 is complete
iter 458 is complete
iter 459 is complete
iter 460 is complete
iter 461 is complete
iter 462 is complete
iter 463 is complete
iter 464 is complete
iter 465 is complete
iter 466 is complete
iter 467 is complete
iter 468 is complete
iter 469 is complete
iter 470 is complete
iter 471 is complete
iter 472 is complete
iter 473 is complete
iter 474 is complete
iter 475 is complete
iter 476 is complete
iter 477 is complete
iter 478 is complete
iter 479 is complete
iter 480 is complete
iter 481 is complete
iter 482 is complete
iter 483 is complete
iter 484 is complete
iter 485 is complete
iter 486 is complete
iter 487 is complete
iter 488 is complete
iter 489 is complete
iter 490 is complete
iter 491 is complete
iter 492 is complete
iter 493 is complete
iter 494 is complete

In [5]:
train_set

,Change,Change1,Change2,Change3,Change4,Change5,Change6,Change7,Change8,Change9,...,Change230,Change231,Change232,Change233,Change234,Change235,Change236,Change237,Change238,Change239
2017-01-03,-0.191659,0.079512,-0.222474,0.165794,-0.345733,-0.253288,0.443128,-0.167007,-0.031421,-0.056073,...,1.318270,-0.518296,-0.493644,-0.271777,0.091838,0.406150,-0.567600,0.289053,-0.715511,0.646506
2017-01-04,0.079512,-0.222474,0.165794,-0.345733,-0.253288,0.443128,-0.167007,-0.031421,-0.056073,0.412313,...,-0.518296,-0.493644,-0.271777,0.091838,0.406150,-0.567600,0.289053,-0.715511,0.646506,-0.277940
2017-01-05,-0.222474,0.165794,-0.345733,-0.253288,0.443128,-0.167007,-0.031421,-0.056073,0.412313,0.054860,...,-0.493644,-0.271777,0.091838,0.406150,-0.567600,0.289053,-0.715511,0.646506,-0.277940,-0.031421
2017-01-06,0.165794,-0.345733,-0.253288,0.443128,-0.167007,-0.031421,-0.056073,0.412313,0.054860,-0.080725,...,-0.271777,0.091838,0.406150,-0.567600,0.289053,-0.715511,0.646506,-0.277940,-0.031421,0.098001
2017-01-09,-0.345733,-0.253288,0.443128,-0.167007,-0.031421,-0.056073,0.412313,0.054860,-0.080725,-0.006769,...,0.091838,0.406150,-0.567600,0.289053,-0.715511,0.646506,-0.277940,-0.031421,0.098001,-0.019095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-08-09,0.398644,-0.626070,0.293704,-1.514979,0.880136,0.769023,0.602352,-0.416189,0.701120,-0.558167,...,-0.576686,-0.335940,0.466547,0.855445,1.028288,-0.070502,0.664082,0.485066,-0.484092,-0.033464
2019-08-12,-0.626070,0.293704,-1.514979,0.880136,0.769023,0.602352,-0.416189,0.701120,-0.558167,-1.817455,...,-0.335940,0.466547,0.855445,1.028288,-0.070502,0.664082,0.485066,-0.484092,-0.033464,-0.521130
2019-08-13,0.293704,-1.514979,0.880136,0.769023,0.602352,-0.416189,0.701120,-0.558167,-1.817455,1.491261,...,0.466547,0.855445,1.028288,-0.070502,0.664082,0.485066,-0.484092,-0.033464,-0.521130,-0.014945
2019-08-14,-1.514979,0.880136,0.769023,0.602352,-0.416189,0.701120,-0.558167,-1.817455,1.491261,-0.545822,...,0.855445,1.028288,-0.070502,0.664082,0.485066,-0.484092,-0.033464,-0.521130,-0.014945,1.077672
2019-08-15,0.880136,0.769023,0.602352,-0.416189,0.701120,-0.558167,-1.817455,1.491261,-0.545822,0.182590,...,1.028288,-0.070502,0.664082,0.485066,-0.484092,-0.033464,-0.521130,-0.014945,1.077672,-0.471746

In [6]:
median = dataset_target.median(axis=1)

In [7]:
median

Date
2017-01-03    0.0065
2017-01-04    0.0088
2017-01-05   -0.0021
2017-01-06    0.0032
2017-01-09   -0.0055
               ...
2021-06-21    0.0191
2021-06-22    0.0004
2021-06-23   -0.0021
2021-06-24    0.0061
2021-06-25    0.0066
Length: 1128, dtype: float64

In [8]:
dataset_target = pd.concat([dataset_target, median], axis = 1)

In [9]:
dataset_target = dataset_target.rename({0:'Median'}, axis='columns')

In [10]:
cnt = 0
for i in range(0, len(dataset_target.columns)-1):
    name  = "Change" + str(cnt)
    dataset_target.loc[dataset_target[name] < dataset_target['Median'], name] = -100
    dataset_target.loc[dataset_target[name] >= dataset_target['Median'], name] = 100
    dataset_target.loc[dataset_target[name] == 100, name] = 1
    dataset_target.loc[dataset_target[name] == -100, name] = 0
    cnt +=1

In [11]:
dataset_target

,Change0,Change1,Change2,Change3,Change4,Change5,Change6,Change7,Change8,Change9,...,Change486,Change487,Change488,Change489,Change490,Change491,Change492,Change493,Change494,Median
Date,,,,,,,,,,,,,,,,,,,,,
2017-01-03,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0065
2017-01-04,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0088
2017-01-05,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,-0.0021
2017-01-06,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0032
2017-01-09,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,-0.0055
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-21,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0191
2021-06-22,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0004
2021-06-23,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.0021
2021-06-24,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0061
2021-06-25,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0066

In [12]:
dataset_target_shift = dataset_target.shift(240)

In [13]:
dataset_target_shift = dataset_target_shift.dropna()

In [14]:
dataset_target_shift

,Change0,Change1,Change2,Change3,Change4,Change5,Change6,Change7,Change8,Change9,...,Change486,Change487,Change488,Change489,Change490,Change491,Change492,Change493,Change494,Median
Date,,,,,,,,,,,,,,,,,,,,,
2017-12-14,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0065
2017-12-15,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0088
2017-12-18,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,-0.0021
2017-12-19,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0032
2017-12-20,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,-0.0055
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-21,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0028
2021-06-22,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,-0.0143
2021-06-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0139
2021-06-24,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,-0.0024
2021-06-25,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0164

In [15]:
# t+1 의 값을 예측하는 것이므로 datashift후 이전 -230과 달리 -229까지 해줘야 한다.
dataset_target_train = dataset_target_shift[:-229]
dataset_target_test = dataset_target_shift[-229:]

In [16]:
dataset_target_train

,Change0,Change1,Change2,Change3,Change4,Change5,Change6,Change7,Change8,Change9,...,Change486,Change487,Change488,Change489,Change490,Change491,Change492,Change493,Change494,Median
Date,,,,,,,,,,,,,,,,,,,,,
2017-12-14,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0065
2017-12-15,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0088
2017-12-18,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,-0.0021
2017-12-19,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0032
2017-12-20,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,-0.0055
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-07-23,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,-0.0057
2020-07-24,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,-0.0125
2020-07-27,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0127
2020-07-28,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,-0.0302
2020-07-29,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0025

In [17]:
train_target_set = dataset_target_train[dataset_target_train.columns[0]]
train_target_set

Date
2017-12-14    0.0
2017-12-15    0.0
2017-12-18    0.0
2017-12-19    0.0
2017-12-20    1.0
             ...
2020-07-23    1.0
2020-07-24    1.0
2020-07-27    1.0
2020-07-28    0.0
2020-07-29    0.0
Name: Change0, Length: 659, dtype: float64

In [18]:
for i in range(1,len(dataset_target_train.columns)-1):
    iter_target_set = dataset_target_train[dataset_target_train.columns[i]]
    train_target_set = pd.concat([train_target_set, iter_target_set], axis= 0)

In [19]:
train_target_set

Date
2017-12-14    0.0
2017-12-15    0.0
2017-12-18    0.0
2017-12-19    0.0
2017-12-20    1.0
             ...
2020-07-23    1.0
2020-07-24    1.0
2020-07-27    0.0
2020-07-28    1.0
2020-07-29    1.0
Length: 326205, dtype: float64

In [20]:
train_target_set.to_csv('trainData/train_target_set.csv')

In [21]:
col_name = []
for i in range(0,240):
    name = 'Sequence' + str(i)
    col_name.append(name)

In [22]:
train_set.columns = col_name

In [23]:
train_set.to_csv('trainData/train_set.csv')